### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by Azarattum** [square/svelte-store#1]
I came to this project after the Svelte Summit talk and it looks very promising (pun intended). 

I just wanted to ask what would be the canonical way to handle errors? For example, when your post request to update fails how do you restore to the state before the optimistic update without refetching all the data from an api? Is it done automatically on a failed promise? Also, what happens if a get request fails due to network issues? Will load promise still resolve with the previous data?

By the way, the idea behind this project is awesome. I’ve been thinking to build something myself to solve similar problems. You did a great work :)

**Comment by Akolyte01** [comment]
Great question! And thank you :)

Before covering writing I'll detail how things work for reading. For the 'readable' aspect of the async stores, calling 'load' on a store will give you a promise that corresponds to the most recent* load. So if there is a problem during loading calling `.load()` will get you that promise rejection. This is also the case for failures in any parents of the store. If any parents fail to load the child will not attempt to load and will retain its initial value, and calling load on the store will give you a promise rejection. 

For writing things are currently left a little bit more to the user to handle. One feature of asyncWritable stores is that the async function you provide for the `mappingWriteFunction` (third argument) can either return void or return a value. If it returns a value, the store will be set to this new value once the asynchronous behavior is complete. This theoretically allows for the catching or errors and deciding what the final value should be in the case of a network failure. 
But you bring up a good point! As the mappingWriteFunction does not have access to the previous value of the store, there is currently not a good way to reset to this previous value in case something goes wrong, short of reloading whatever store the data ultimately comes from. 

I'll take some time to consider whether it would be appropriate for the store to perform that action automatically as well as alternative options like surfacing the previous value of the store to the `mappingWriteFunction`

**Comment by Akolyte01** [comment]
@Azarattum I have made a pull request that should address your concern.
https://github.com/square/svelte-store/pull/4

As an example of how this would work
```
const myWritable = asyncWritable(
  parents,
  loadFunction,
  async (newValue, parentValues, oldValue) => {
    try {
      return await presistToBackend(newValue);
    } catch {
      return oldValue;
    }
  }
);
```
Thus network failures would be caught, and the store set back to its old value. 

Does this sound like it supports what you had in mind?

**Comment by Azarattum** [comment]
It does feel a little bit boilerplaty having to handle this in userland. Especially since the optimistic updates are handled by the library itself. Also position of the arguments looks a little bit awkward, but I guess this is for backwards compatibility. Other than that, this is exactly what I was hoping for! Thank you!

**Comment by Akolyte01** [comment]
Yeah it is more boiler plate than is ideal, however I don't think it's safe to perform this step 'for' the user. 
In Square's use case for example we wouldn't want a deleted element to suddenly pop back into existence and would instead display an error banner if there is a problem.

**Comment by Akolyte01** [comment]
So when it comes to writing the ideal behavior here is going to change on a case by case basis. With that in mind asyncWritable should default to not being opinionated here, and doing nothing on failure is the most neutral behavior. 

I think I"m going to add a flag 'persistToBackend' that can be optionally provided to 'set' or 'update' to indicate whether the asynchronous behavior should be performed or not (defaults to yes). This would provide an additional way to handle this scenario--catching a set error and then setting to the old value without persisting.
