### ISSUE TITLE
How can I return a unsubscribe function?

### ISSUE THREAD

**Issue by samklingdev** [square/svelte-store#13]
Using a normal svelte store, the return value from a readable or writable would be a function thats being called on unsubscribe. 
But I cannot figure out how to return a unsubscribe function with asyncReadable or asyncWritable.

**Comment by Akolyte01** [comment]
Hey there, sorry for the delayed response.

Could you describe your use case for this? `subscribe` will return a default unsubscriber as per normal stores, but yes there is not currently a way to provide a custom unsubscribe callback to an async store the way you can for readable and writable stores.

The reasoning here is that these async stores are intended for data hydration of an application--where data loading happens in a linear order.  For asynchronous applications that require cleanup, like a store updating when an event listener or interval fires, then the idea was that regular readable and writable stores already do a good job there and should continue to be used.

So with some more info about your use case we can determine if existing tools can appropriately address it, or if we need some additional functionality added to the package.

**Comment by samklingdev** [comment]
In my case, I had a WebSocket that I wanted to clean up. But as you say, I realized that It was much better to use the normal readable for this.
