### ISSUE TITLE
Question: Async reentrant safety of load?

### ISSUE THREAD

**Issue by coldino** [square/svelte-store#17]
It is possible to want to access the contents of a single async store from multiple places. Is it necessary for application code to prevent multiple concurrent (async concurrent, not thread) calls to its `load` function to prevent duplicate fetches, for example? This of course extends to the entire derived tree and becomes much more complicated for the application.

Having looked at the source I *think* this is correctly prevented. Having done some basic testing it also looks to avoid duplicate processing. Still, I thought it was better to ask to make it clear.

**Comment by Akolyte01** [comment]
> It is possible to want to access the contents of a single async store from multiple places. Is it necessary for application code to prevent multiple concurrent (async concurrent, not thread) calls to its `load` function to prevent duplicate fetches, for example? This of course extends to the entire derived tree and becomes much more complicated for the application.
> 
> Having looked at the source I _think_ this is correctly prevented. Having done some basic testing it also looks to avoid duplicate processing. Still, I thought it was better to ask to make it clear.

Hey there! There's no need to avoid multiple calls to `load` a store. Calling `load` will always give you access to the current load process. This means you'll only ever generate a new fetch request if you designate the store as `reloadable` and call `reload` on it, or if it derives from any stores and the values of those stores change.

**Comment by coldino** [comment]
Wonderful. Thanks for the clarification.
