### ISSUE TITLE
Why load and reload are optional?

### ISSUE THREAD

**Issue by fbjorn** [square/svelte-store#19]
Hi,

I'm using TypeScript and since `load` and `reload` are optional in stores, I need to write my code like this:

```svelte
export let asyncStore: Loadable<unknown>

asyncStore.reload?.()

{#await asyncStore.load?.()}
    <div />
{:then} 
    <div />
{/await}
```

What is the point they are optional? Is there some use case when your store doesn't have them?

**Comment by Akolyte01** [comment]
Prior to version 0.2.0, derived stores would only include a load function if they derived from at least one store with a load function. In this way, calling `load` on a store where that performed no action would throw an error. This is how reloadable works currently. 
In 0.2.0 all stores now include a load function, and the Loadable type was updated to make `load` required. 

Additionally, the optional chaining requirement is a toggleable feature of Typescript strict mode, which I'm personally of the opinion as counter-productive for Svelte.

**Comment by fbjorn** [comment]
Thanks for the answer 🙂
