### ISSUE TITLE
Readable/Writable load functions cannot be reset/reloaded in tests

### ISSUE THREAD

**Issue by brandonmarino** [square/svelte-store#21]
### Introduced in: v0.2.0

```
const hasConsent = actionWritable((set) => {
    const setConsent = set(true);
    addEventListener('CONSENT_EVENT', setConsent);

    return () => removeEventListener('CONSENT_EVENT', setConsent);  
});
```

This works perfectly for production purposes, however I'm running into issues in testing. How should we reload or reset this store in a test environment? 

### What I have tried:
- Using `flagForReload` which is defined by the `Loadable<any>` type. I received the following error: `flagForReload is not a function`. Seems like we have some divergence between the type and exposed functions for readable/writable.
- Setting the store back to `undefined`. This had no affect on the load state.

I can see from your discussions [here](https://github.com/square/svelte-store/issues/14#issuecomment-1191811682) that this is intended for one off situations and shouldn't be able to be reset. I believe we need to be able to reset these stores in testing environments.

**Comment by Akolyte01** [comment]
I'm not sure if there's an appropriate way to 'reload' readable/writable stores.  Unlike async stores readable/writable do not have a load function and instead have a start function. As such they do not have any capacity to be 'reloaded', do not ever have a 'reload' function, and thus can't be flagged for reload. 

Flagging an async for reload also does not reset an async store to an unloaded state--it just forces the store to run it's load function again the next time the store is subscribed to. 

Some specifics of the use case you are trying to test might be necessary here to determine the best solution.

**Comment by Akolyte01** [comment]
Closing this barring some more information. Feel free to reopen with some specific examples :)
