### ISSUE TITLE
asyncDerived can create duplicate subscriptions

### ISSUE THREAD

**Issue by dpmccabe** [square/svelte-store#26]
I have a component that's only displayed conditionally. Inside that component, I have an `asyncDerived` store that derives from a writable store that's defined in a global `stores.js` file.

### App.svelte

```
{#if displayMyComponent}
<MyComponent />
{/if}
```

### MyComponent.svelte

```js
<script>
import { writable, asyncDerived } from '@square/svelte-store';
import { searchText } from 'stores';

const sortCol = writable('foo');

const myStore = asyncDerived(
  [searchText, sortCol],
  async ([theSearchText, theSortCol]) => {
    console.log('updating');
    return await getData(theSearchText, theSortCol);
  },
  false
);
</script>
```

### stores.js

```js
import { writable } from '@square/svelte-store';

export const searchText = writable('');
```

The first time `displayMyComponent` becomes true and the component is displayed, the stores work as expected.

However, when `displayMyComponent` is toggled from `false` back to `true`, thus destroying and reloading the component, whenever the value `searchText` changes, the derived function runs twice: I see "updating" twice in the console and `getData` produces two identical network requests. Toggling the display flag again produces triplicate behavior.

Notably, this duplication doesn't happen when the value of `sortCol` changes no matter how many times the component is destroyed and reloaded. I don't think this happens when you're using plain Svelte derived stores, either.

It seems like there needs to be an unsubscription that happens when the component is destroyed. Is there something I can put in `onDestroy` that will break the dependency between `searchText` and `myStore`? Or a better way to define `myStore`?

**Comment by Akolyte01** [comment]
Certainly seems to be a bug. I do not have an immediate suggestion for a work around beyond a general recommendation to avoid defining stores within components when possible. Often [reactive statements ](https://svelte.dev/tutorial/reactive-statements) are a better choice for component specific functionality. Of course I don't know your use case so that might not be applicable.

I will look into this. Thank you for reporting!

**Comment by Akolyte01** [comment]
@dpmccabe should be fixed! let me know if you have any problems
