### ISSUE TITLE
How to delay the asyncDerived store kicking off until previous writeable has completed?

### ISSUE THREAD

**Issue by sureshjoshi** [square/svelte-store#60]
I have two stores, and I'm trying to figure out how to sync them up correctly. Using MockServiceWorkerJS, I seem to get into a problem that I'm requesting my updated Posts object before the starredStore has had the chance to finish its update handler.

Is there a way to delay updating downstream stores until the upstream ones have completed their updates?

```svelte
export const starredStore: WritableLoadable<string[]> = asyncWritable(
  [],
  async () => {
    const response = await fetch(`/starred`);
    // Error handling
    return await response.json();
  },
  async (newStarred) => {
    const postBody = JSON.stringify(newStarred);
    const response = await fetch(`/starred`, {
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
      },
      body: postBody,
    });
    // Error handling
    return newStarred;
  }
);


export const starredPosts: Loadable<any[]> = asyncDerived(
  starredStore,
  async (_) => {
    const response = await fetch(`/posts`);
    // Error handling
    return await response.json();
  }
);
```

**Comment by Akolyte01** [comment]
So this is a bit unintuitive for your use case, but the way asyncWritable stores write functionality works is that when you call `starredStore.set` the store's value will immediately update then kick off the asynchronous behavior, then will update again with the value returned by the asynchronous function (if the value is different).

The reason for that is that the supported use case is to persist changes made in the app. In your use case if a user changes what is "starred" you (probably) wouldn't want to wait until that network call finished before updating the display state of your application. So the store value updates immediately, allowing your app to update as soon as the user makes the change, and then you can perform a secondary update depending on the results of the PUT if needed.

However the side effect of this is what you've observed: the derivation step of starredPosts will begin as soon as you call `starredStore.set` and not when it has finished. 

I think the key here is that the relationship between /starred and /posts is not managed by your app but is instead implicit through your backend. The async behavior of starredPosts doesn't actually need to wait for the value of starredStore, you just need it to update when starred updates.  As a result, though you are deriving from starredStore, you aren't actually using its value in starredPosts. You may want to reconsider whether you use derivation at all in this case. 

instead I would do something like the following:
```
export const starredStore.... // as is

export const starredPosts = asyncReadable(
  undefined, 
  async () => {
    const response = await fetch(`/posts`);
    // Error handling
    return await response.json();
  },
  { reloadable: true }
);

export const setStarred = async (newStarred) => {
  await starredStore.set(newStarred);
  await starredPosts.reload();
}
```

**Comment by sureshjoshi** [comment]
Ah, thanks! 

The library is awesome, and has cleaned up a ton of stuff. The behaviour I'm seeing definitely makes sense per my understanding of the library, but I didn't know if there was some mechanism/flag for deferring/delaying the downstream derived stores until the async write/update completed. I didn't see it in code, but one can always hope :) 

What you've suggested makes sense too. The starred post thing was definitely this weird, race-condition prone, implicit problem - which I had planned to fix in the long term, but was hoping to patch around it in the short term.

I think this imperative reload could be the right approach. 

In fact, if it wasn't for a silly star icon I need to place on the UI for these starred posts, my solution would be adequate enough - but because of the timing of the potential call, the UI gets slightly out of sync.

I'll try your suggestion tonight and see if that patches my UI bugs.

Thanks again!

**Comment by Akolyte01** [comment]
No problem! Glad the package can be of help. An alternative approach could be to use a single asyncWritable store for starred and posts (holding {starred: [], posts: []} for example) and then using derived stores to grab the relevant data. Then in your async writable function you would query for the new /posts data after PUTing the new /starred data, then return both from the async function so that the store updates with the new data when it finishes set.

However I think my first suggestion would be more manageable. Good luck!
