### ISSUE TITLE
Svelte 4 support

### ISSUE THREAD

**Issue by Akolyte01** [square/svelte-store#67]

**Comment by jwrunge** [comment]
For anyone looking to get up and running with Svelte 4.0 in the short-term, the usually terrible idea of using `npm install @square/svelte-store --force` seems to get the job done with no obvious ill effects.

**Comment by Akolyte01** [comment]
AFAIK there are no incompatabilities between svelte 4 and the package..... however it does not like how the tests are set up so I have not been able to confirm this yet.

**Comment by Akolyte01** [comment]
closed via https://github.com/square/svelte-store/pull/76

**Comment by samuller** [comment]
Until a new version with that fix is released, I've found I can avoid my CI jobs needing to `npm install` with `--force` by adding an `overrides` section to my `package.json` (e.g. below `"devDependencies"`):

```json
	"overrides": {
		"@square/svelte-store": {
			"svelte": ">= 3.0.0 < 5.0.0"
		}
	},
```

**Comment by velut** [comment]
If using `pnpm` you can add the following to `package.json`:

```jsonc
{
  // Inside package.json
  "pnpm": {
    "peerDependencyRules": {
      "allowedVersions": {
        "@square/svelte-store@1>svelte": "4"
      }
    }
  }
}
```

See https://pnpm.io/package_json#pnpmpeerdependencyrulesallowedversions.
