### ISSUE TITLE
Error at demo code

### ISSUE THREAD

**Issue by bangdragon** [square/svelte-store#77]
Errror at demo code at https://codesandbox.io/embed/square-svelte-store-demo-tbvonh?file=/App.svelte&codemirror=1

When click on x icon, there is error:
```
_stores.suggestedBlogs.reload is not a function
```

**Comment by bangdragon** [comment]
It seems the demo code is old
const personalizedBlogs = asyncDerived(
  userToken,
  ($userToken) => {
    return personalization.getPersonalizedBlogs($userToken);
  },
  true
);

I replace ``` true ``` at the end with
```
  { reloadable: true }
```

**Comment by jaclas** [comment]
Please try to remove any item from list:

TypeError
_stores.suggestedBlogs.reload is not a function

**Comment by bangdragon** [comment]
@jaclas thanks, the problem is solved as my above comment
